#if you guys wanna win a prize you must have to do this and if you lie to use saying we did it then you wont be wining anything


#this might take a long time for you to answer because it might be hard on moble but on any pc or laptop it will be ezer just press ctrl enter in your keyboard and the command the command will be running in console, you can answer the question by tyeping when it come to your trun for example whats 1+1 then under the question it says you:. then your allowed to type if you get the answer wrong it still makes you keep on going. remember if you get 3 wrongs your going to have to reset and start all over goob luck on everythig :P goob luck on everything.!!
#remember for any question you may not be aloeed to use calculator. why? because this test is for you to see if you got the maths in your barin and if you use the calculator you wont be able to understand any proleams ofc if you cant figure on out you may but i dont think so you are going to need anything for this like a calculator. thank you you may start.

print("welcome to math games this is 1st garde if you guys win this you guys will be in the next grade")
name = input("you: ")
print("1st question is what is 1+1")
name = input("you:")
print("nice you got this right lets get to the next one what is 1+2")
name = input("you; ")
print(" nice one your going great 3 question is what is 2+2")
name = input(" you:")
print("nice you got this right to your going insane at this moment next question what is 3+2")
name = input("you:")
print("nice you got that right now you have 5 secands of brake got get what you need")
name = input("you:")
print(" welcome back your in the next level remember the question will get hrader each time you get this right remember to take this serious ")
name= input("you:")
print("welcome to 2 grade")
name = input("you:")
print("what is 1 times 1")
name = input("you:")
print("nice job! you got it right!!")
name = input("you:")
print("what is 1 times 2 ")
name = input("you:")
print("nice job you got that right lets move on to the next question")
name = input("you:")
print("what is 2 times 2")
name = input("you:")
print(" nice job take a 5 secand brake ")
name = input("you:")
print("welcome to 3 grade ")
name = input("you:")
print(" what is 10 times 5")
name = input("you:")
print(" nice job! your doing insane")
name = input("you:")
print("welcome to 4th grade its going to get harder remember that ")
name = input("you:")
print("slove this answer adam has 5 apples and jack has 5 apples how many do they have in all?")
name = input("you:")
print("nice job")
name = input("you:")
print("ahmed has 25 apples ashley has 10 apples how many to they have in together remember what dose how many mean? answer it down in you: boz")
name = input("you:")
print(" nice job you got that right to take a 5 min barke if you would like to")
name = input("you:")
print(" welcome back from the 5 min barke are you ready for more? well lets get into it ")
name = input("you:")
print("if jacke had 25 bannas and amy has five and she toke 5 away from jacke how much will jacke have A,15 B10, C20, D25 remember to read the question strongly")
name = input("you:")
print("nice job you got this right you have passed 4th grade now you are in 5th grade the math proleams will get hrader each time you move up a grade ")
name = input("you:")
print("what is 3 divided by 2")
name =input("you:")
print("nice job you got this right")
name = input("you:")
print("what is 10 divided by 5")
name = input("you:")
print("nice job you got this one right you might not get this one :/")
name = input("you:")
print("what is 700 divided 5?")
name = input("you:")
print("nice job! you got it right")
name = input("you:")
print("nice job you have been graduated!. welcome to 6th grade it will be getting hrader")
name = input("you:")
print("what is 3/2 times 4/2")
name = input("you:")
print("nice job you got it right")
name = input("you:")
print("what is 4/10 + 5/1")
name = input("you:")
print(" nice job you got it right!!")
name = input("you:")
print("now what is 1/5 times 3/1")
name = input("you:")
print("nice job you got that right")
name = input("you:")
print("this is the last math question you will be getting for 6th grade you are moving really fast there")
name = input("you:")
print(" what is 10 to the power of 5 remember this is something you didnt learn in out code youu take your time and this will be the math you will be learning in 7th grade ")
nane = input("you:")
print("nice job you got that right! welcome to 7th grade you may use the bathmrom or drink some water for the next question you will be given  ")
name = input("you: ")
print("Erin loves to play sports! She has earned 333 tennis trophies, 444 basketball trophies, 777 soccer trophies, and 111 volleyball trophy.  What is the ratio of Erin's tennis trophies to soccer trophies? Choose 1 answer: A: 3:7 B: 4:7 C: 7:4 D: 3:12")
name = input("you:")
print("IF you got D iNCORRECt if you got c iNCORRECT if you got b iNCORRECT the right answer was A")
name = input("you:")
print("What is the ratio of cookies to ice cream cones? 3 cookies and 1 ice cream A 1 to 3 B 3 to 1or C 1 to 4 Or D 4 to 1")
name = input("you:")
print(" if you got A you are iNCORRECT if you got B you are right ")
name = input("you:")
print("Katie loves to read! In the last few months she has read 333 graphic novels, 222 mysteries, 444 sci-fi novels, and 212121 comic books. What is the ratio of sci-fi novels to comic books? Choose 1 answer: A 21:30 B 4:21 C 4:26 or D 21:4")
name = input("you:")
print(" if you got A your iNCORRECT if you got b you are right ic you got c your wrong if you got d your wrong")
name = input("you")
print("nice job you are now 8th grade last grade then you move on to high school")
name = input("you:")







print(" nice job this is still being edited :)))")



